### ISSUE TITLE
Please make formal release

### ISSUE THREAD

**Issue by jonassmedegaard** [zaf/Asterisk-eSpeak#2]
Hi,

Last formal release was in 2011, and I notice some commits since then.

Please consider make a formal release.

**Comment by zaf** [comment]
I guess I got lazy and followed the comfort trend of rolling releases on github:P
I will tag the latest trunk code as version 2.2 stable.

**Comment by jonassmedegaard** [comment]
Quoting Lefteris Zafiris (2015-05-17 20:19:50)
> I guess I got lazy and followed the comfort trend of rolling releases on
> github:P
> I will tag the latest trunk code as version 2.2 stable.

Thanks!

I maintain the packaging of Asterisk-eSpeak officially for Debian.  
Formally releasing is an indication of what you consider "stable", and 
is far easier for distributors to track than just git commits.

...and yes, I do believe that some people in this World still use good 
old distributions like Debian, shipping with prebuilt binaries. :-)


 - Jonas

-- 
 * Jonas Smedegaard - idealist & Internet-arkitekt
 * Tlf.: +45 40843136  Website: http://dr.jones.dk/

 [x] quote me freely  [ ] ask before reusing  [ ] keep private

**Comment by zaf** [comment]
2.2 stable is out. 
Changes have been minimal and haven't got any bug reports for quite some time, I guess we can label it stable even by debian standards ;)
Thank you for  taking the time to add this to debian.
