### ISSUE TITLE
A wrong voice name causes asterisk to crash

### ISSUE THREAD

**Issue by chlohr** [zaf/Asterisk-eSpeak#3]
Hi,
  Asterisk crashes if one choose a non-existing voice. 
The proposed patch may fix it.

Regards
Christophe

[app_espeak.patch.txt](https://github.com/zaf/Asterisk-eSpeak/files/111375/app_espeak.patch.txt)

**Comment by zaf** [comment]
Thank you very much Christophe, Your fix was merged.
