### ISSUE TITLE
Build Issue on CentOS 6 with Asterisk 11

### ISSUE THREAD

**Issue by joshelson** [zaf/Asterisk-eSpeak#4]
This is the make output:

https://gist.github.com/joshelson/caf74173c1be46730b09082f58f66ce6

**Comment by zaf** [comment]
Please try checking out v3.0 and trying to compile this against asterisk 11. Trunk is updated and tested against asterisk 14 so some things might break with older asterisk versions.

**Comment by joshelson** [comment]
That worked great:

git checkout tags/v3.0
