### ISSUE TITLE
cant install

### ISSUE THREAD

**Issue by Montana357** [zaf/Asterisk-eSpeak#8]
hello, im trying to setup the eSpeak module with eSpeak from yum repo on centos 6

[root@sip Asterisk-eSpeak]# make
gcc -pipe -fPIC -Wall -Wextra -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations -D_REENTRANT -D_GNU_SOURCE -DAST_MODULE_SELF_SYM=__internal_app_espeak_self -g -O2                                                              -c -o app_espeak.o app_espeak.c
app_espeak.c:39:33: error: espeak-ng/speak_lib.h: No such file or directory
app_espeak.c:40:24: error: samplerate.h: No such file or directory
app_espeak.c:150: error: expected declaration specifiers or ‘...’ before ‘espeak_EVENT’
app_espeak.c: In function ‘synth_callback’:
app_espeak.c:153: error: ‘events’ undeclared (first use in this function)
app_espeak.c:153: error: (Each undeclared identifier is reported only once
app_espeak.c:153: error: for each function it appears in.)
app_espeak.c: In function ‘raw_resample’:
app_espeak.c:169: error: ‘SRC_DATA’ undeclared (first use in this function)
app_espeak.c:169: error: expected ‘;’ before ‘rate_change’
app_espeak.c:198: warning: implicit declaration of function ‘src_short_to_float_array’
app_espeak.c:204: error: ‘rate_change’ undeclared (first use in this function)
app_espeak.c:210: warning: implicit declaration of function ‘src_simple’
app_espeak.c:210: error: ‘SRC_SINC_FASTEST’ undeclared (first use in this function)
app_espeak.c:212: warning: implicit declaration of function ‘src_strerror’
app_espeak.c:212: warning: format ‘%s’ expects type ‘char *’, but argument 7 has type ‘int’
app_espeak.c:221: warning: implicit declaration of function ‘src_float_to_short_array’
app_espeak.c: In function ‘espeak_exec’:
app_espeak.c:247: error: ‘espeak_ERROR’ undeclared (first use in this function)
app_espeak.c:247: error: expected ‘;’ before ‘espk_error’
app_espeak.c:255: warning: missing initializer
app_espeak.c:255: warning: (near initialization for ‘args.text’)
app_espeak.c:315: warning: implicit declaration of function ‘espeak_Initialize’
app_espeak.c:315: error: ‘AUDIO_OUTPUT_SYNCHRONOUS’ undeclared (first use in this function)
app_espeak.c:319: warning: implicit declaration of function ‘espeak_SetSynthCallback’
app_espeak.c:320: warning: implicit declaration of function ‘espeak_SetVoiceByName’
app_espeak.c:320: error: ‘EE_OK’ undeclared (first use in this function)
app_espeak.c:324: warning: implicit declaration of function ‘espeak_SetParameter’
app_espeak.c:324: error: ‘espeakRATE’ undeclared (first use in this function)
app_espeak.c:328: error: ‘espeakVOLUME’ undeclared (first use in this function)
app_espeak.c:332: error: ‘espeakWORDGAP’ undeclared (first use in this function)
app_espeak.c:336: error: ‘espeakPITCH’ undeclared (first use in this function)
app_espeak.c:350: error: ‘espk_error’ undeclared (first use in this function)
app_espeak.c:350: warning: implicit declaration of function ‘espeak_Synth’
app_espeak.c:350: error: ‘POS_CHARACTER’ undeclared (first use in this function)
app_espeak.c:351: error: ‘espeakCHARS_AUTO’ undeclared (first use in this function)
app_espeak.c:352: warning: implicit declaration of function ‘espeak_Terminate’
make: *** [app_espeak.o] Error 1

**Comment by zaf** [comment]
As the log shows the required build dependencies are not installed:

`app_espeak.c:39:33: error: espeak-ng/speak_lib.h: No such file or directory
app_espeak.c:40:24: error: samplerate.h: No such file or directory`

Please install the required packages before building.
